### ISSUE TITLE
Unable to download a book

### ISSUE THREAD

**Issue by designer91** [ritiek/scribd-downloader#33] opened 2018-12-31 19:20 UTC
scribdl https://fr.scribd.com/read/382268615/SQL-Server-2017-Integration-Services-Cookbook
Traceback (most recent call last):
  File "c:\users\nabil\appdata\local\programs\python\python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\nabil\appdata\local\programs\python\python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Nabil\AppData\Local\Programs\Python\Python37-32\Scripts\scribdl.exe\__main__.py", line 5, in <module>
  File "c:\users\nabil\appdata\local\programs\python\python37-32\lib\site-packages\scribdl\__init__.py", line 3, in <module>
    from .downloader import Downloader
  File "c:\users\nabil\appdata\local\programs\python\python37-32\lib\site-packages\scribdl\downloader.py", line 8, in <module>
    from .pdf_converter import ConvertToPDF
  File "c:\users\nabil\appdata\local\programs\python\python37-32\lib\site-packages\scribdl\pdf_converter.py", line 1, in <module>
    from md2pdf.core import md2pdf
  File "c:\users\nabil\appdata\local\programs\python\python37-32\lib\site-packages\md2pdf\__init__.py", line 3, in <module>
    from md2pdf.core import (
  File "c:\users\nabil\appdata\local\programs\python\python37-32\lib\site-packages\md2pdf\core.py", line 3, in <module>
    from weasyprint import HTML, CSS
  File "c:\users\nabil\appdata\local\programs\python\python37-32\lib\site-packages\weasyprint\__init__.py", line 394, in <module>
    from .css import preprocess_stylesheet  # noqa
  File "c:\users\nabil\appdata\local\programs\python\python37-32\lib\site-packages\weasyprint\css\__init__.py", line 25, in <module>
    from . import computed_values
  File "c:\users\nabil\appdata\local\programs\python\python37-32\lib\site-packages\weasyprint\css\computed_values.py", line 17, in <module>
    from .. import text
  File "c:\users\nabil\appdata\local\programs\python\python37-32\lib\site-packages\weasyprint\text.py", line 14, in <module>
    import cairocffi as cairo
  File "c:\users\nabil\appdata\local\programs\python\python37-32\lib\site-packages\cairocffi\__init__.py", line 41, in <module>
    cairo = dlopen(ffi, 'cairo', 'cairo-2', 'cairo-gobject-2')
  File "c:\users\nabil\appdata\local\programs\python\python37-32\lib\site-packages\cairocffi\__init__.py", line 38, in dlopen
    raise OSError("dlopen() failed to load a library: %s" % ' / '.join(names))
OSError: dlopen() failed to load a library: cairo / cairo-2 / cairo-gobject-2

**Comment by ritiek** [comment] 2018-12-31 19:30
Duplicate of #17. Check out the instructions for installing the missing library here https://github.com/Kozea/CairoSVG/issues/84 and then try again. Let me know if it fixes for you.

**Comment by designer91** [comment] 2019-01-02 23:54
Thank you for your reply 
I solved the problem with the help of your guidance :)

Best Regards!

**Comment by ritiek** [comment] 2019-01-03 03:59
That's good to know. :)

I'll close this issue then.

**Closed** 2019-01-03 03:59 UTC
Labels: duplicate
